package pl.nikowis.librin.model;

public enum OfferCategory {
    BIOGRAPHIES_REPORTS_FACT,
    JOURNALS_MAGAZINES,
    FOR_CHILDREN,
    FOR_YOUTH,
    FANTASY_SCIFI_HORROR,
    HISTORICAL,
    COMIC_BOOK_MANGA,
    CRIME_SENSATION_THRILLER,
    POPULAR_SCIENCE,
    FOREIGN_LANGUAGE,
    COOKING_DIETS,
    NOVEL,
    ROMANCE_EROTIC,
    SCHOOL_AND_ACADEMICAL,
    BELLES_LETTRES,
    SPECIALIST_LITERATURE,
    ART,
    GUIDEBOOKS_PERSONAL_GROWTH,
    TOURISM_TRAVEL_SPORT_LEISURE,
    OTHER,
}

